### PR TITLE
Make structure similar to react-starter

### PR DESCRIPTION
**Pull request by eliperelman**
This PR just tries to add a little more structure similar to the React starter.

### CODE REVIEW

**Comment by helfi92** [comment]
HMR worked on a single DOM change. Subsequent changes to the DOM fails to hot reload properly. The page refreshes instead. Can you replicate this behavior?

**Comment by eliperelman** [comment]
@helfi92 I can replicate, but I have no idea what the problem is. I'll investigate.

**Comment by eliperelman** [comment]
I can't explain it, but it seems to boil down to the usage of `replaceChild`.

**Comment by helfi92** [comment]
I'm not sure we want to take this approach. Closing for now.

**Pull request closed without merging**
